EMAIL_TEAM_MAP = {
    "pamsupport@titan.co.in": "Infosec",
    "abhijithcnair@titan.co.in": "Infosec",
    "venkats@titan.co.in": "Infosec",
    "controltowerteam@titan.co.in": "Infosec",
    "thulasidhasan_m@titan.co.in": "ECOM",
    "vimal.kumar@titan.co.in": "Analytics",
    "anaawsadmins@titan.co.in": "Analytics",
    "arunbalasubramaniam@titan.co.in": "Analytics",
    "avi_kumar@titan.co.in": "EyePlus",
    "ananda.sekhar@titan.co.in": "Jewellery",
    "kamaladass@titan.co.in": "ECOM",
    "varunkumar@titan.co.in": "Watches",
    "muruganandham@titan.co.in": "ECOM",
    "ganesh_b@titan.co.in": "Jewellery",
    "naveenn@titan.co.in": "EyePlus",
    "dineshbalaji.a@caratlane.com": "Caratlane",
    "donam@titan.co.in": "Jewellery",
    "jamess@titan.co.in": "Jewellery",
    "goverdhanak@titan.co.in": "Jewellery",
    "manohargvnd@titan.co.in": "Wearables",
    "bhuwan@thoughtsutra.com": "Corp HR",
    "harbhajan.singh@netcarrots.com": "CRM",
    "arijitdas@titan.co.in": "Jewellery",
    "mrinalkumar@deloitte.com": "CRM",
    "shivshankar@titan.co.in": "Corp HR",
    "prasenjeet@karnival.com": "CRM",
    "senthilkumar.ct@titan.co.in": "TEAL",
    "shivachapagai@titan.co.in": "Infosec",
    "harshac@titan.co.in": "OCI",
    "suryaprakash@titan.co.in": "Infosec",
    "lokesh_k@titan.co.in": "Infosec",
    "edrsupport@titan.co.in": "Infosec",
    "reassign to csrc perimeter security platinum": "Infosec",
    "lokesh_v@titan.co.in": "Jewellery",
    "nirajprasad@titan.co.in": "Watches",
    "veluruarun@titan.co.in": "Analytics",
    "pramodkumar@titan.co.in": "Corp HR",
    "anaibmadmin@titan.co.in": "Analytics",
    "sathiamoorthy@titan.co.in": "Others",
    "sunkararavi@titan.co.in": "Analytics",
    "linuxsupport@titan.co.in": "Infosec",
    "joshuaa@titan.co.in": "Taneria",
    "kvprasad@titan.co.in": "Corp HR",
    "shivakumar@titan.co.in": "Jewellery",
    "shivaniupadhyay@titan.co.in": "Corp HR",
    "santhoshkumarreddy@titan.co.in": "Watches",
    "pbalaji@titan.co.in": "Corp HR",
    "dhanushya@titan.co.in": "Watches",
    "panchalchittilappilly@titan.co.in": "IBD",
    "periakaruppans@titan.co.in": "Infosec",
    "venkatareddyv@titan.co.in": "Corp HR",
    "sapbasis@titan.co.in": "SAP",
    "sanjeevm13@titan.co.in": "Watches",
    "iseadmin@titan.co.in": "Infosec",
    "pankajkumar@titan.co.in": "Oracle",
    "fathimakadhoonm@titan.co.in": "Infosec",
    "mssupport@titan.co.in": "Infosec",
    "cadadmin@titan.co.in": "Infosec",
    "sankararaman@titan.co.in": "TEAL",
    "dbasupport@titan.co.in": "Database",
    "kathir@titan.co.in": "Jewellery",
    "premak@titan.co.in": "Jewellery",
    "arunvasam@titan.co.in": "Watches",
    "anavindhyas@titan.co.in": "Analytics",
    "abhi.pandit@titan.co.in": "Analytics-AIML"
}
